name: ğŸ› ï¸ Build
 
on:
  workflow_dispatch:
 
jobs:
  build:
    runs-on: windows-latest
 
    steps:
    - name: â¬‡ï¸ Checkout code
      uses: actions/checkout@v4
 
    - name: âš™ï¸ Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly-2025-12-06
        targets: x86_64-pc-windows-msvc
 
    - name: ğŸ”¨ Build
      run: cargo build --release
 
    - name: â¬†ï¸ Upload patch
      uses: actions/upload-artifact@v4
      with:
        name: sonetto-patch
        path: target/release/
